# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }


    app.mailer.notification:
        class: AppBundle\Mailer\NotificationMailer
        arguments:
            - 'Spotizer'
            - 'spotizer@clever-age.com'
            - '@templating'
            - '@mailer'

    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
    admin.blog_post:
        class: AppBundle\Admin\BlogPostAdmin
        arguments: [~, AppBundle\Entity\BlogPost, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog post }
    # Repositories
    app.repository.track:
        class: AppBundle\Repository\TrackRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Track']

    app.repository.artist:
        class: AppBundle\Repository\ArtistRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Artist']

    app.repository.playlist:
        class: AppBundle\Repository\PlaylistRepository
        factory: ['@doctrine', 'getRepository']
        arguments: ['AppBundle:Playlist']