homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: "%locale%"
    requirements:
        _locale: en|fr|es
sanocelo_context:
    path: /{_locale}/context
    defaults:
            _controller: AppBundle:Default:context

sanocelo_vision:
    path: /{_locale}/notre-vision
    defaults:
        _controller: AppBundle:Default:notreVision
        _locale: "%locale%"
    requirements:
        _locale: en|fr|es

sanocelo_solutions:
    path: /{_locale}/nos-solutions
    defaults:
        _controller: AppBundle:Default:solutions
        _locale: "%locale%"
    requirements:
        _locale: en|fr|es

sanocelo_partenaires:
    path: /{_locale}/partenaires
    defaults:
        _controller: AppBundle:Default:partenaires
        _locale: "%locale%"
    requirements:
        _locale: en|fr|es

sanocelo_medias:
    path: /{_locale}/medias
    defaults:
        _controller: AppBundle:Default:medias
        _locale: "%locale%"
    requirements:
        _locale: en|fr|es

sanocelo_contact:
    path: /{_locale}/contact/
    defaults:
        _controller: AppBundle:Default:contact
        _locale: "%locale%"
